### PR TITLE
Add async task cancel listener and multiple waypoint support

### PR DESCRIPTION
**Pull request by deepankarb**
1. I have added a callback wrapper for [AsyncTask.OnCancelled()](http://developer.android.com/reference/android/os/AsyncTask.html#onCancelled()), useful if any UI modification is done in the other callbacks (onSuccess/onFailure). If the user moves away from the activity while directions are still being calculated then we can simply discard the results and avoid touching the UI at all.

2. Added rudimentary support for multiple waypoints as per [Using Waypoints in Routes](https://developers.google.com/maps/documentation/directions/#Waypoints)

### CODE REVIEW

**Comment by jd-alexander** [comment]
Thanks for the contribution. I'm going to add support for adding multiple points because at the moment only a start and endpoint is accepted when executing the routing functionality. 
` start = new LatLng(18.015365, -77.499382);
        end = new LatLng(18.012590, -77.500659);

        Routing routing = new Routing(Routing.TravelMode.WALKING);
        routing.registerListener(this);
        routing.execute(start, end);`

I'm wondering if  I should just add a method overload with a list of waypoints as the argument. Thoughts?

**Comment by deepankarb** [comment]
The `AsyncTask.execute()` method takes in a variable number of arguments, so there is no need to modify any code outside of the `Routing` task. I have added support for handling more than two arguments inside the `constructURL(LatLng... points)` method. That's all! Example usage:

```java
        waypoints[0] = srcLatLng;
        waypoints[size - 1] = dstLatLng;

        for (int i = 1; i < size - 1; i++) {
            waypoints[i] = new LatLng(latLngList.get(i).getLatitude(), latLngList.get(i).getLongitude());
        }

        routingTask = new Routing(Routing.TravelMode.DRIVING);
        routingTask.registerListener(this);
        routingTask.execute(waypoints);
```

`Routing.execute()` method signature remains same so existing code is not broken. Except if less than two points are specified then an exception is thrown.

**Comment by ankit-maverick** [comment]
@deepankarb @jd-alexander :+1: for this PR. Would like to see this merged as early as possible!!

**Comment by jd-alexander** [comment]
Ok going to merge now

**Comment by jd-alexander** [comment]
@deepankarb Yeah I just looked at the async task and remembered that it can accept multiple points in that format. Thanks for pointing that out.

**Comment by jd-alexander** [comment]
Deployed a new version 1.0.2 . You can try it via gradle. Haven't updated
readme as yet or tested.. Let me know if it works. Want to ensure the sync
I made with maven was good.

**Comment by deepankarb** [comment]
Great. Thanks!

**Comment by ankit-maverick** [comment]
@deepankarb @jd-alexander : Not sure where it's going wrong but I am getting `onRoutingFailure` when I pass the LatLng Array `routingTask.execute(waypoints)` instead of `routingTask.execute(start, end)`.

**Comment by ankit-maverick** [comment]
@deepankarb @jd-alexander : It works good with the old usual `routingTask.execute(start, end)`

**Comment by jd-alexander** [comment]
Ok I'm going to check it out

**Comment by jd-alexander** [comment]
What's the error being returned. Check the log cat to see if the library
outputted anything

**Comment by jd-alexander** [comment]
@deepankarb why are you explicitly setting the length of the string buffer ? I'm gonna change to string builder and run a test and see how it works.

**Comment by ankit-maverick** [comment]
@jd-alexander : I think the length of the string buufer is being set to remove the last `|`

**Comment by jd-alexander** [comment]
@ankit-maverick Yeah. I'm gonna try and fix it soon. I have some other work I have to attend to so hold tight.

**Comment by ankit-maverick** [comment]
@jd-alexander : sure, thanks. Meanwhile, I will update here if I find some clue.

@deepankarb : Can you post an example code that worked while you were testing?

**Comment by ankit-maverick** [comment]
@jd-alexander @deepankarb : Apologies for causing the panic. I had a silly bug because of which I was getting `onRoutingFailure`. The code by @deepankarb works great, :+1:

**Comment by jd-alexander** [comment]
haha okay. I was about to run some test. Glad it all works.

**Pull request merged**
