### PR TITLE
Make models Parcelable

### PR DESCRIPTION
**Pull request by tamhuynhit**
I need some of the models to be Parcelable so that I can pass them through Activities, save and restore from Bundle as well.
Please take a look

### CODE REVIEW

**Comment by jd-alexander** [comment]
Hey thanks for the addition. I am no longer releasing new version of the library so you would have to just release the forked copy for Parcelable support.

**Comment by tam0407** [comment]
Thanks for the advice, I will check that solution

**Comment by jd-alexander** [comment]
No problem

**Comment by saber34bba** [comment]
hello jd-alexander 
can i use your project about Google-Directions-Android  in my project then share it
i hope that you answer me 
good job

**Comment by jd-alexander** [comment]
@saber34bba  yes you can.

**Pull request merged**
