### PR TITLE
update Segment.java

### PR DESCRIPTION
**Pull request by vincenzoiacovone**
Field 'maneuver' managed. This field contains instructions like 'turn-left' or 'turn-right', useful to custom icons management

### CODE REVIEW

**Comment by vincenzoiacovone** [comment]
Thank you! Where i can find the new version on gradle?

Date: Thu, 21 Apr 2016 09:43:52 -0700

**Comment by vincenzoiacovone** [comment]
When*

From: vincenzo.iacovone@live.it
To: reply@reply.github.com
Subject: RE: [jd-alexander/Google-Directions-Android] update Segment.java (#55)
Date: Fri, 22 Apr 2016 12:06:12 +0200




Thank you! Where i can find the new version on gradle?

Date: Thu, 21 Apr 2016 09:43:52 -0700

**Comment by jd-alexander** [comment]
I'm publishing that today.

Joel Dean,
Software Engineer

**Comment by jd-alexander** [comment]
Sorry for not publishing as yet. My computer crashed so taking a day to get it up and running.

**Pull request merged**
