### PR TITLE
Added the option to select between alternative routes

### PR DESCRIPTION
**Pull request by gawdzer**
Added the option to select between alternative routes (shortest, fastest) where RouteMode.FASTEST is the default.

Usage:

            Routing routing = new Routing.Builder()
                    .travelMode(AbstractRouting.TravelMode.DRIVING)
                    .routeMode(AbstractRouting.RouteMode.SHORTEST)
                    .withListener(this)
                    .waypoints(start, end)
                    .build();

### CODE REVIEW

**Comment by jd-alexander** [comment]
Ok great. what's causing the conflict..a bit busy to check right now.

**Comment by gawdzer** [comment]
@jd-alexander no idea. I can't seem to find any conflicts. I tried merging pull request  #31 into my fork but it didn't seem to help.

**Comment by gawdzer** [comment]
@jd-alexander Sorry for the mess. Had to sync my fork with master - I resolved the conflicts now.

**Comment by jd-alexander** [comment]
Okay. I  am gonna review and merge with  main branch soon.

**Comment by jd-alexander** [comment]
You tested this and it  works well ? I can't test right now. I am going to push to maven once I know all is fine.

**Comment by gawdzer** [comment]
Yes - tested and verified that it works

**Comment by jd-alexander** [comment]
Awesome

**Comment by jd-alexander** [comment]
Could you give me a link to the part of the Google directions  documentation where this is present?

**Comment by gawdzer** [comment]
https://developers.google.com/maps/documentation/directions/intro#RequestParameters - optional parameters

**Comment by jd-alexander** [comment]
Thanks

**Comment by jd-alexander** [comment]
Question. So doesn't the API return the shortest route by default? Like what's necessarily the difference between the shortest/fastest? arent they the same thing.

**Comment by gawdzer** [comment]
Given a list of routes from A to B, the shortest route is one such as there
does not exist another route in the list where it's distance is smaller
than the shortest's route distance

The fastest route (default which google returns) is the route which takes
less time to drive (considering toll roads, traffic, etc)

So short = minimal distance from A to B
Fast = minimal travel time from A to B

**Comment by jd-alexander** [comment]
Oh I understand now. Thanks for the clarification.

**Pull request merged**
