### PR TITLE
refactor builder

### PR DESCRIPTION
**Pull request by YusukeHata**
I refactored Routing builder class.
Please review.

Example
```java
Routing routing = new Routing.Builder(start, end)
        .travelMode(AbstractRouting.TravelMode.DRIVING)
        .avoid(AbstractRouting.AvoidKind.HIGHWAYS)
        .waypoints(point1, point2)
        .withListener(this)
        .build();
routing.execute();
```

### CODE REVIEW

**Comment by jd-alexander** [comment]
Okay why is this builder accepting start and end when there's a waypoints
function for that ?

**Comment by YusukeHata** [comment]
This is typograph. sorry.
```
.waypoints(end, start)
```

below code is right.
```
Routing routing = new Routing.Builder(start, end)
        .travelMode(AbstractRouting.TravelMode.DRIVING)
        .avoid(AbstractRouting.AvoidKind.HIGHWAYS)
        .waypoints(point1, point2)
        .withListener(this)
        .build();
routing.execute();
```

start and end are necessary.
But waypoints is optional.
So constructor is accepted start and end.

**Comment by jd-alexander** [comment]
Even though start and end are necessary that doesn't mean only a constructor can ensure they are added while chaining the builder. You can simply throw an exception if they are null. Check this builder of a popular android library https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java

**Comment by YusukeHata** [comment]
Thanks for replying.
Which is better for Ａ or B ?

A
```
Routing routing = new Routing.Builder()
        .start(start)
        .end(end)
        .build();
```

B
waypoints contain start and end.
```
Routing routing = new Routing.Builder()
        .waypoints()
        .build();
```

**Comment by jd-alexander** [comment]
B remember that the waypoints are a list of points. Not just two . Look at
the param of the routing async task

**Comment by YusukeHata** [comment]
Thanks for replying.
I change Builder class.
Please review.


```java
List<LatLng> waypoints = new ArrayList<>();
waypoints.add(start);
waypoints.add(end);            
Routing routing = new Routing.Builder()
        .waypoints(waypoints)
        .build();
```
or
```java
LatLng[] waypoints = new LatLng[] {start, end};
Routing routing = new Routing.Builder()
	    .waypoints(waypoints)
	    .build();
```

**Comment by jd-alexander** [comment]
the second one. the waypoints functions should accept multiple LatLngs..and its parameter should be of type LatLng... points  so developers can pass in the points without explicitly declaring the array. http://stackoverflow.com/questions/11640507/difference-between-arrays-and-3-dots-in-java

**Comment by YusukeHata** [comment]
Now, The waypoints function accept LatLng... parameter as below.

```
Builder waypoints (LatLng... points) {
```
https://github.com/YusukeHata/Google-Directions-Android/blob/d1c0b97518c0e23f0295ed8b8b583d4f6c5c6677/library/src/main/java/com/directions/route/Routing.java#L90-Lundefined

Is it wrong?

**Comment by jd-alexander** [comment]
No thats alright.

**Comment by YusukeHata** [comment]
rebase done

**Comment by jd-alexander** [comment]
Okay but I still see the builder accepting a start and endpoint..wanted to just use waypoints alone...so the constructor of the builder would be empty.

**Comment by YusukeHata** [comment]
The constructor of the builder doesnt accept start and endpoint at latest commit.

https://github.com/YusukeHata/Google-Directions-Android/blob/d2d8e1e7b3b03564e296d0996c8c80a1ede3a24c/library/src/main/java/com/directions/route/Routing.java#L78-L83

I'm not good at English.sorry.

**Comment by jd-alexander** [comment]
Ok it's looking great. The example has been updated and you tested right ?

**Comment by YusukeHata** [comment]
sure.

**Comment by jd-alexander** [comment]
Okay I am a bit busy. Could you update the example in the read me to the new route builder class. Once that's done I will merge your code and then push new update to maven.

**Comment by YusukeHata** [comment]
Update README.md.
Please review.

**Comment by jd-alexander** [comment]
Ok great work thanks alot! Merging now.

**Pull request merged**
