### PR TITLE
support avoid parameters

### PR DESCRIPTION
**Pull request by YusukeHata**
hi. Google-Directions-Android is very nice.
I will use Google-Directions-Android for my app. 

I support avoid parameters.
Please review.

Example
```java
Routing routing = new Routing.Builder(Routing.TravelMode.DRIVING)
        .avoid(Routing.AvoidKind.HIGHWAYS)
        .build();
routing.registerListener(this);
routing.execute(start, end);
```

thanks

### CODE REVIEW

**Comment by jd-alexander** [comment]
Merged but then I noticed that the builder being used could be a bit more streamlined. It would be nice if you add a method to set the travel mode such `Routing.Builder()
.travelMode(TravelMode.DRIVING)
.avoid(AvoidKind.HIGHWAYS)
.withListener(this)
.waypoints(start,end).build();

routing.execute();`

**Comment by YusukeHata** [comment]
thank you review.
I will improve builder soon.

**Comment by jd-alexander** [comment]
alright.

**Comment by YusukeHata** [comment]
if I will improve builder, below code can't be compiled.
Is that OK?

```
Routing routing = new Routing(Routing.TravelMode.WALKING);
routing.execute(start, end);
```

**Comment by jd-alexander** [comment]
yes therefore it wil be updated. the sample can be updated likewise

**Comment by YusukeHata** [comment]
I understand. thanks

**Pull request merged**
